-- Purchase Orders: supplier orders with item snapshots (one supplier per order).
-- Run with: npx prisma migrate deploy

CREATE TABLE `PurchaseOrder` (
  `id` VARCHAR(191) NOT NULL,
  `tenantId` VARCHAR(191) NOT NULL,
  `referenceNumber` VARCHAR(191) NOT NULL,
  `name` VARCHAR(191) NULL,
  `status` VARCHAR(191) NOT NULL DEFAULT 'PENDING',
  `supplierId` VARCHAR(191) NULL,
  `supplierName` VARCHAR(191) NOT NULL,
  `supplierEmail` VARCHAR(191) NULL,
  `items` LONGTEXT NOT NULL,
  `currency` VARCHAR(191) NOT NULL DEFAULT 'CHF',
  `totalNet` DOUBLE NOT NULL DEFAULT 0,
  `totalGross` DOUBLE NOT NULL DEFAULT 0,
  `revision` INTEGER NOT NULL DEFAULT 0,
  `emailSentAt` DATETIME(3) NULL,
  `emailRecipient` VARCHAR(191) NULL,
  `stockedAt` DATETIME(3) NULL,
  `createdByEmpId` VARCHAR(191) NULL,
  `createdAt` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  `updatedAt` DATETIME(3) NOT NULL,
  PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;

-- Reference numbers are generated by max-scan; the unique key makes collisions
-- fail loudly so the route can retry with the next sequence value.
CREATE UNIQUE INDEX `PurchaseOrder_tenantId_referenceNumber_key` ON `PurchaseOrder`(`tenantId`, `referenceNumber`);
CREATE INDEX `PurchaseOrder_tenantId_idx` ON `PurchaseOrder`(`tenantId`);
CREATE INDEX `PurchaseOrder_status_idx` ON `PurchaseOrder`(`status`);
CREATE INDEX `PurchaseOrder_supplierId_idx` ON `PurchaseOrder`(`supplierId`);
